### ISSUE TITLE
On macOS netclient often does not call wg-quick down

### ISSUE THREAD

**Issue by taladar** [gravitl/netclient#204]
I can't quite narrow it down to the exact circumstances but with about half of our macOS users netclient does not take down the VPN interface on `netclient disconnect -n <network name>`

Is there any way to run netclient with more logging or details beyond the --vvvv option which doesn't show anything relevant?

**Comment by mattkasun** [comment]
v0.18.X changes the manner in which wg interfaces (now only one) are created, updated and deleted.
