### ISSUE TITLE
Support IPv6 endpoint

### ISSUE THREAD

**Issue by ftiasch** [gravitl/netclient#266]
I use v0.17.1 for both servers and clients and I tried to set the endpoint of `node6` to a IPv6 address. 

However, `netclient` (on another node) refused to join showing 

```
[netclient] 2023-03-12 09:01:42 error installing:  error creating node 500 Internal Server Error {"Code":500,"Message":"address 2408:---:---:---:----:---:----:----:-----: too many colons in address"}
```

(The `-` symbol is used for privacy).

What can I do?

**Comment by mattkasun** [comment]
where did you change the endpoint?

**Comment by mattkasun** [comment]
no response, closing
