### ISSUE TITLE
ubuntu - netclient package not found using steps provided in the docs

### ISSUE THREAD

**Issue by semtex41** [gravitl/netclient#327]
Hello, 
I followed these instructions but was not able to locate the package. 

https://netmaker.readthedocs.io/en/master/netclient.html#installation

`E: Unable to locate package netclient`

Fresh install:
Distributor ID:	Ubuntu
Description:	Ubuntu 22.10
Release:	22.10
Codename:	kinetic

**Comment by markgabrang** [comment]
Exactly the same thing with 22.04 LTS

**Comment by zarevskaya** [comment]
On Debian server 10 it's the same.

Have a nice day :)

**Comment by imightbelosthere** [comment]
> On Debian server 10 it's the same.
> 
> Have a nice day :)

Could it be because it isn't the stable version and the source.list declares a stable version?

**Comment by mattkasun** [comment]
installation verified -  version v0.19.0
