### ISSUE TITLE
netclient v0.17.1 version not exis?

### ISSUE THREAD

**Issue by baerwang** [gravitl/netclient#357]

**Comment by ajarmoszuk** [comment]
Same here, can't install 17.1 and 18.6 has broken routing.

**Comment by bose2273** [comment]
same here could not find 17.1

**Comment by bose2273** [comment]
Take a look at this .. might help you ....
https://github.com/gravitl/netmaker/issues/2219#issuecomment-1515053076

**Comment by baerwang** [comment]
thx,me at link got it `https://github.com/gravitl/netmaker/releases/tag/v0.17.1`
