### ISSUE TITLE
0.18.7 Windows msi installer bug - desktop and menu start shortcuts to wrong file

### ISSUE THREAD

**Issue by nicrame** [gravitl/netclient#372]
I'm at Win10 x64 and just installed 0.18.7 from .msi package. It created desktop and menu start icons that are pointing to the wrong file - 
netclient.exe. But in this release the file name that is installed is "netclient-windows-amd64.exe". So when i click on the file Windows always ask to find destination file.
I've attached screenshots.

![Zrzut ekranu (991)](https://user-images.githubusercontent.com/5872054/234685190-f448954e-3aff-4d9c-ae8d-aec19df81532.png)
![Zrzut ekranu (992)](https://user-images.githubusercontent.com/5872054/234685196-0151f638-9228-4ab9-87d7-7d34921f59cd.png)

**Comment by theguy951357** [comment]
Thank you for letting me know. just hotfixed it. the installer should install netclient.exe now.
