### ISSUE TITLE
Defunct project?

### ISSUE THREAD

**Issue by thekrugers** [gravitl/netclient#395]
The Windows MSI installer is 404, the Powershell command to install tries to download a netclient.exe that is also 404.

Has this project been abandoned? Or has a decision just been made to stop supporting Windows cleints?

**Comment by nicrame** [comment]
I already informed about this error in here: https://github.com/gravitl/netmaker-docs/issues/127

The best place to download newest clients is here: https://github.com/gravitl/netclient/releases
The project is developing but this is still very early version (0.XX) and it's lacking of man power. Things are developed slow, and fixing things take a lot of time. No easy upgrades for server or clients, many things do not work after updates etc. But i see progress, and i believe it may be very great tool one day.
