### ISSUE TITLE
Missing dependencies in docker image causing netclient to conclude there is no iptables/firewall support

### ISSUE THREAD

**Issue by jalbstmeijer** [gravitl/netclient#413]
In https://github.com/gravitl/netclient/issues/307 we found missing packages can cause netclient to conclude there is no iptables/firewall support

Initially with versions v0.18.0/19.0 the error was triggered by the missing 'wg' binary for which package wireguard-tools is needed.  (it's used in the endpoint startup script too on cleanup)

With v0.20.0 adding the wireguard-tools package was not enough anymore. Now it seems missing the ip6tables package causes netclient to conclude there is no iptables/firewall support.

For now it seems to work with this workaround in the docker compose file

```
entrypoint: bash -c "apk add wireguard-tools ip6tables; /bin/bash netclient.sh"
```

So two requests here:
- Add these packages in the docker image or remove the dependency if possible.
- Make netclient more verbose about the reason it concludes there is no iptables/firewall support

**Comment by mattkasun** [comment]
netclient docker images include iptables and iptables56
