### ISSUE TITLE
release changelog suggestion

### ISSUE THREAD

**Issue by jalbstmeijer** [gravitl/netclient#469]
With each release a section "What's Fixed" is included on the release page.
In most cases I suppose something was fixed based on a reported issue.
Can I suggest to mention the issue numbers as a link for each item in that  "What's Fixed" list?

Not sure if automating it is feasible like mentioned here;

https://www.7pace.com/blog/how-to-link-github-issues-to-github-releases

But adding the issue numbers manually would already be very helpful

**Comment by mattkasun** [comment]
--In most cases I suppose something was fixed based on a reported issue.--

most issues are found internally.  When a fix is related to issue, the issue should be linked with PR number.  See https://github.com/gravitl/netclient/issues/454  for example
