### ISSUE TITLE
Options --name --port missing ?

### ISSUE THREAD

**Issue by julienym** [gravitl/netclient#499]
Documented here: https://docs.netmaker.io/advanced-client-install.html#cli-reference

The version of netclient 0.20.2 from apt doesn't have those arg. available, nor those the config file is used...

Any idea how to setup name and port ?

Thanks

**Comment by mattkasun** [comment]
docs need updating;  you can see the valid flags by running netclient -h

**Comment by julienym** [comment]
Hi @mattkasun, any pointers on controlling more options from the client? It's missing many options for my current setup. Thanks

**Comment by mattkasun** [comment]
> Hi @mattkasun, any pointers on controlling more options from the client? It's missing many options for my current setup. Thanks

Not from netclient directly, but you can use nmctl to update the same parameters as through the UI
