### ISSUE TITLE
Filed based config

### ISSUE THREAD

**Issue by wexder** [gravitl/netclient#503]
Is there a way how to configure netclient via some configuration files ? This would be useful for non interactive environments.

**Comment by wexder** [comment]
I can see that there are some configurations files. But they don't look particularly user friendly. My idea was something like being able to put the invite key into config file and netclient would use it at startup, or something like that.
Currently it's impossible to use netclient in deployments oriented around infrastructure as code

**Comment by mattkasun** [comment]
our CI workflow deploys a netmaker network using terraform several times a day.  The terraform scripts are available at https://github.com/gravitl/devops/tree/master/qa/terraform/branchterraform



Note that these scripts are for CI and will not be updated to support general deployments but you are welcome to adapt the scripts to your use case.
