### ISSUE TITLE
[Feature Request] Add a `--force` option to Netclient leave to let it continue if it can't connect to the Netmaker server.

### ISSUE THREAD

**Issue by Southpaw1496** [gravitl/netclient#534]
This would be useful in situations where the client is no longer able to connect to the server because of Netmaker. For example, recently Netmaker assigned one of my clients an IP that also happened to be the IP that it uses for DNS (that was my fault), so it was unable to send DNS requests and connect to the server to disconnect itself from the network. I had to completely uninstall the client in order to get DNS functionality to return. If I had a `--force` option, to continue even if the server connection failed, I would not have had to reinstall it.

**Comment by mattkasun** [comment]
netclient leave will remove the network from the client even if server is not reachable.

**Comment by qiuzi** [comment]
I also want the client to stay still until the server is turned on and updated
