### ISSUE TITLE
Modifying /etc/hosts causing issues

### ISSUE THREAD

**Issue by purepani** [gravitl/netclient#607]
I am a NixOS user, and one of the changes NixOS makes is that /etc/hosts is symlinked from the nix store, which is read only. 
The issue this causes is when using the DNS integration, since /etc/hosts can't be modified, nothing is populated into there. 

I was also thinking this might cause other conflicts with other programs that might also try to modify /etc/hosts. Is there a way to work around this, or would that require integrating a different solution for dns resolution into netclient?

**Comment by mattkasun** [comment]
there is no workaround

**Comment by purepani** [comment]
Thanks,
I'll try and look harder for a solution on the Nixos side

**Comment by mattkasun** [comment]
No plans that I am aware of

**Comment by wexder** [comment]
@mattkasun so there's no chance of running netclient with dns integration on distributions like Nixos ?

**Comment by mattkasun** [comment]
Not with current implementation
